### ISSUE TITLE
The "name, copyright holder and authority" input column can only accept Latin characters

### ISSUE THREAD

**Issue by Taiwania** [Toollabs/relgen#9]
@FDMS, the "name, copyright holder and authority" input column I tested are not accept any other languages but only Latin characters. Because non-Latin multilingual characters (like CJK) are appeared, could you fix them to accept the multilingual characters? Thanks.

**Comment by Artoria2e5** [comment]
The blame goes to all these `\w` stuff in JS Regex: https://github.com/toollabs/relgen/blob/master/express.php#L46

Maybe use [Unicode's regex translator](http://unicode.org/cldr/utility/list-unicodeset.jsp) to do some [`\p{L}\p{Nd}_`](http://unicode.org/cldr/utility/list-unicodeset.jsp?a=%5Cp%7BL%7D%5Cp%7BNd%7D_&abb=on&c=on&esc=on&g=&i=)? Or just grab some XRegExp from npm and make some fancy browser packing magic...

**Comment by Artoria2e5** [comment]
Um well, these are defined locally for each PHP file. I might still prefer some refactoring to de-duplicate the regexes though.

By the way I wonder if we can make a translation for the `express` version...

**Comment by FDMS** [comment]
Will look into these suggestions (and also ping @zhuyifei1999). Re translating the express version be aware that even the English express version is quite rarely used ([two times](https://tools.wmflabs.org/relgen/stats.php) so far this year) – still, feel free to provide a translation under i18n/zh-hant-express.php (open to other paths or names).

**Comment by zhuyifei1999** [comment]
@FDMS what does this part of code do? I don't find a hint from `v`, `namei`, `fg1`. I'll see if I can find an alternative besides using regexes.

**Comment by Artoria2e5** [comment]
@zhuyifei1999, I should've linked the relevant sections in zh-tw's code. These are the same regexen though.

**Comment by FDMS** [comment]
Implemented per off-GitHub discussions.
